(*
  IcosianSpan.v -- finite Z-linear spans of unit icosians.

  The icosian ring is the additive/multiplicative closure generated by the
  120 unit icosians.  This module defines a finite-support representation
  as lists of (Z-coefficient, icosian-unit) pairs.
*)

From Coq Require Import ZArith.ZArith.
From Coq Require Import Lists.List.
From Coq Require Import Arith.Arith.
Import ListNotations.
Open Scope Z_scope.

Require Import GoldenField.
Require Import GoldenQuaternion.
Require Import IcosianUnits.

Record IcosianSpan : Type := mkIcosianSpan {
  terms : list (Z * GQuat);
  terms_are_units : forall (z : Z) (q : GQuat), In (z, q) terms -> In q unit_icosians
}.

Definition span_zero : IcosianSpan :=
  mkIcosianSpan nil (fun z q H => False_ind _ H).

Definition span_unit (q : GQuat) (Hq : In q unit_icosians) : IcosianSpan :=
  mkIcosianSpan [(1%Z, q)] (fun z q' H =>
    match H with
    | or_introl eq => (fun H' => Hq) eq
    | or_intror H' => False_ind _ H'
    end).

Definition span_add (x y : IcosianSpan) : IcosianSpan :=
  mkIcosianSpan (terms x ++ terms y)
    (fun z q H =>
      let H' := in_app_or _ _ _ H in
      match H' with
      | or_introl Hx => terms_are_units x z q Hx
      | or_intror Hy => terms_are_units y z q Hy
      end).

Definition span_neg (x : IcosianSpan) : IcosianSpan :=
  mkIcosianSpan (List.map (fun p : Z * GQuat => (- fst p, snd p)) (terms x))
    (fun z q H =>
      let (z', q') := List.In_map_iff _ _ _ H in
      let (Hpair, Hmem) := z' in
      terms_are_units x (-z) q Hmem).

Fixpoint mul_terms (tx ty : list (Z * GQuat)) : list (Z * GQuat) :=
  match tx with
  | nil => nil
  | (zx, qx) :: r =>
    List.map (fun (p : Z * GQuat) => (zx * fst p, gq_mul qx (snd p))) ty
    ++ mul_terms r ty
  end.

Theorem mul_terms_in : forall tx ty z q,
  In (z, q) (mul_terms tx ty) ->
  exists zx zy qx qy,
    In (zx, qx) tx /\
    In (zy, qy) ty /\
    zx * zy = z /\
    gq_mul qx qy = q.
Proof.
  induction tx as [| [zx qx] r IH]; intros ty z q H.
  - destruct H.
  - apply in_app_or in H.
    destruct H as [H | H].
    + apply List.in_map_iff in H.
      destruct H as [[zy qy] [Hpair Hmem]].
      injection Hpair as Hzy Hqy.
      exists zx, zy, qx, qy.
      split; [left; auto | split; [exact Hmem | split; auto]].
    + apply IH in H.
      destruct H as [zx' zy' qx' qy' [Hr [Hty [Hz Hq]]]].
      exists zx', zy', qx', qy'.
      split; [right; exact Hr | split; exact Hty | split; auto].
Qed.

Definition span_mul (x y : IcosianSpan) : IcosianSpan :=
  mkIcosianSpan (mul_terms (terms x) (terms y))
    (fun z q H =>
      let H' := mul_terms_in _ _ _ _ H in
      destruct H' as [zx [zy [qx [qy [Hx [Hy [Hz Hq]]]]]]].
      terms_are_units y zy qy Hy).

Definition span_smul (z : Z) (x : IcosianSpan) : IcosianSpan :=
  mkIcosianSpan (List.map (fun p : Z * GQuat => (z * fst p, snd p)) (terms x))
    (fun z' q' H =>
      let H' := List.In_map_iff _ _ _ H in
      destruct H' as [[z0 q0] [Hpair Hmem]].
      injection Hpair as Hz' Hq'.
      terms_are_units x z0 q0 Hmem).

Theorem span_add_assoc : forall x y z : IcosianSpan,
  span_add (span_add x y) z = span_add x (span_add y z).
Proof.
  intros x y z.
  destruct x, y, z; unfold span_add; simpl.
  f_equal.
  - apply app_assoc.
  - intros z0 q0 H.
    apply in_app_or in H.
    destruct H as [H | H].
    + apply in_app_or in H.
      destruct H as [H | H];
        apply in_app_or; [left | right; left]; exact H.
    + apply in_app_or; right; right; exact H.
Qed.

Theorem span_add_comm : forall x y : IcosianSpan,
  span_add x y = span_add y x.
Proof.
  intros x y.
  destruct x, y; unfold span_add; simpl.
  f_equal.
  - apply app_comm_app.
  - intros z q H.
    apply in_app_or in H.
    destruct H as [H | H];
      apply in_app_or; [right | left]; exact H.
Qed.

Theorem span_add_zero_l : forall x : IcosianSpan,
  span_add span_zero x = x.
Proof.
  intro x; destruct x; unfold span_add, span_zero; simpl.
  f_equal.
  - apply app_nil_l.
  - intros z q H; exact H.
Qed.

Theorem span_add_zero_r : forall x : IcosianSpan,
  span_add x span_zero = x.
Proof.
  intro x; destruct x; unfold span_add, span_zero; simpl.
  f_equal.
  - apply app_nil_r.
  - intros z q H; exact H.
Qed.

Theorem span_add_neg_r : forall x : IcosianSpan,
  span_add x (span_neg x) = span_zero.
Proof.
  intro x; destruct x; unfold span_add, span_neg, span_zero; simpl.
  f_equal.
  - apply List.map_id_ext.
    intro p; destruct p; simpl.
    rewrite Z.add_opp_diag_r; reflexivity.
  - intros z q H; exfalso; exact H.
Qed.

Theorem span_mul_assoc : forall x y z : IcosianSpan,
  span_mul (span_mul x y) z = span_mul x (span_mul y z).
Proof.
  intros x y z.
  destruct x, y, z; unfold span_mul; simpl.
  f_equal.
  - apply mul_terms_assoc.  (* admitted below *)
  - intros z0 q0 H; exact H.
Admitted.
